[package]

# Semantic Versioning is used: https://semver.org/
version = "1.0"

# Description
category = "isaaclab"
readme  = "README.md"

title = "A generic robot RL library based on IsaacLab"
author = "Weishu Zhan"
maintainer = "Weishu Zhan"
description="A generic robot RL library based on IsaacLab"
repository ="https://github.com/fan-ziqi/robot_lab.git"
keywords = ["extension", "RL_lab", "isaaclab"]

[dependencies]
"omni.isaac.lab" = {}
"omni.isaac.lab_assets" = {}
"omni.isaac.lab_tasks" = {}
# NOTE: Add additional dependencies here

[[python.module]]
name = "RL_lab"

[isaaclab_settings]
# TODO: Uncomment and list any apt dependencies here.
#       If none, leave it commented out.
# apt_deps = ["example_package"]
# TODO: Uncomment and provide path to a ros_ws
#       with rosdeps to be installed. If none,
#       leave it commented out.
# ros_ws = "path/from/extension_root/to/ros_ws"
